describe('Formulário de Cliente', () => {

  beforeEach(() => {
    cy.visit('https://qa-training.sbx.devsquad.app/')
    cy.wait(3000)
  })

  it('CT001 - Preencher formulário com dados válidos', () => {
    cy.get('#name').type('João Silva')
    cy.get('input[name="email"]').type('joaoteste@hotmail.com')
    cy.get('input[name="phone"]').type('22999887766')
    cy.get('#dateOfBirth').type('1998-09-24')
    cy.get('#address').type('Rua dos testes, 123 - Rio de Janeiro/RJ')
    cy.get('ui-select').eq(0).click()
    cy.contains('Brazil').click()
    cy.get('ui-select').eq(1).click()
    cy.contains('Rio de Janeiro').click()
    cy.get(':nth-child(2) > #clientType1 > .shrink-0').click()
    cy.get('#annualIncome').type('100000')
    cy.get('.p-6 > :nth-child(10)').click()
    cy.get('.absolute').click()
    cy.contains('Client created successfully!').should('be.visible')
  })

  it('CT002 - Preencher formulário com email inválido', () => {
    cy.get('#name').type('João Silva')
    cy.get('input[name="email"]').type('joaoteste@.com')
    cy.get('input[name="phone"]').type('22999887766')
    cy.get('#dateOfBirth').type('1998-09-24')
    cy.get('#address').type('Rua dos testes, 123 - Rio de Janeiro/RJ')
    cy.get('ui-select').eq(0).click()
    cy.contains('Brazil').click()
    cy.get('ui-select').eq(1).click()
    cy.contains('Rio de Janeiro').click()
    cy.get(':nth-child(2) > #clientType1 > .shrink-0').click()
    cy.get('#annualIncome').type('100000')
    cy.get('.p-6 > :nth-child(10)').click()
    cy.get('.absolute').click()
    cy.contains('The email field must be a valid email address.').should('be.visible')
  })

  it('CT003 - Preencher formulário com dados faltando', () => {
    cy.get('#name')
    cy.get('input[name="email"]').type('joaoteste@hotmail.com')
    cy.get('input[name="phone"]').type('22999887766')
    cy.get('#dateOfBirth').type('1998-09-24')
    cy.get('#address').type('Rua dos testes, 123 - Rio de Janeiro/RJ')
    cy.get('ui-select').eq(0).click()
    cy.contains('Brazil').click()
    cy.get('ui-select').eq(1).click()
    cy.contains('Rio de Janeiro').click()
    cy.get(':nth-child(2) > #clientType1 > .shrink-0').click()
    cy.get('#annualIncome').type('100000')
    cy.get('.p-6 > :nth-child(10)').click()
    cy.get('.absolute').click()
    cy.contains('The name field is required.').should('be.visible')
  })

})